### ISSUE TITLE
How I manage textInput as text is overlapping with Keyboard?

### ISSUE THREAD

**Issue by akshay2792** [AntonyZ89/NotePad-app#1]
@AntonyZ89 Kindly help on this 
![IMG_992A34BDB8E0-1](https://user-images.githubusercontent.com/99638548/225837467-bcb1f100-4fe7-4059-bb9e-eb42a6525fc9.jpeg)

**Comment by AntonyZ89** [comment]
Apologies for the delay, to fix it you can use **KeyboardAvoidingView**

https://reactnative.dev/docs/keyboardavoidingview
